# Generated by Django 5.2 on 2025-09-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorter',
            name='original_url',
            field=models.URLField(blank=True, max_length=128, unique=True),
        ),
    ]
