# Generated by Django 5.2 on 2025-09-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorter', '0002_shorter_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorter',
            name='original_url',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
