# Generated by Django 5.2 on 2025-09-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorter', '0003_alter_shorter_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorter',
            name='url',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
