# Generated by Django 5.2 on 2025-09-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorter', '0004_alter_shorter_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorter',
            name='url',
            field=models.URLField(blank=True, max_length=128, unique=True),
        ),
    ]
